# Site settings
title: Christopher John Bird
description: Homepage of Chris Bird
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://chrisjbird.uk" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chris Bird
user_description: Programmer, Web Developer, Bassist, Yak Shaver...
user_title: Software Developer
email: chrisjbird@gmail.com
twitter_username: drkvogel
github_username:  drkvogel
gplus_username:  +ChrisBird001

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules', 'yarn.lock', 'gulpfile.js', 'pushlive', 'README.md']
